name: Laravel

on:
  push:
    branches: [ "staging", "development", "milestone/*" ]
  pull_request:
    branches: [ "main" ]

jobs:
  development-tests:
    name: Run Test for Development
    if: ${{ github.ref == 'refs/heads/development' }}
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: php artisan test

  environment-tests:
    name: Run test with proper environment
    if: ${{ github.ref != 'refs/heads/development' }}
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Setup DDEV
      uses: ddev/github-action-setup-ddev@v1
    - name: Install Dependencies
      run: ddev composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: ddev artisan key:generate
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      run: ddev artisan test

